Restyled by shfmt

diff --git a/libexec/setzer/setzer-bot b/libexec/setzer/setzer-bot
--- a/libexec/setzer/setzer-bot
+++ b/libexec/setzer/setzer-bot
@@ -19,11 +19,11 @@
 
 #set -ex
 
-function log {
+function log() {
   echo "[$(date "+%D %T")] $1"
 }
 
-function verbose {
+function verbose() {
   [[ $SETZER_VERBOSE ]] && echo "[$(date "+%D %T")] [V] $1"
 }
 
@@ -53,7 +53,10 @@ done
 [[ $SETZER_MEDIANIZER ]] || errors+=("No medianizer set. Please set it via SETZER_MEDIANIZER ")
 #[[ $SETZER_SOURCES ]] || errors+=("No price sources set. Please set them via SETZER_SOURCES ")
 
-[[ ${errors[*]} ]] && { printf '%s\n' "${errors[@]}"; exit 1; }
+[[ ${errors[*]} ]] && {
+  printf '%s\n' "${errors[@]}"
+  exit 1
+}
 
 [[ $SETZER_SPREAD ]] || export SETZER_SPREAD=2
 
@@ -63,7 +66,7 @@ done
 [[ $SETZER_NEXT_EXPIRATION_HOURS ]] || export SETZER_NEXT_EXPIRATION_HOURS=12
 [[ $SETZER_EXPIRES_IN_SECONDS ]] || export SETZER_EXPIRES_IN_SECONDS=3600
 
-max_gas=$(seth --to-wei 500 gwei 2> /dev/null || echo 500000000000 )
+max_gas=$(seth --to-wei 500 gwei 2>/dev/null || echo 500000000000)
 [[ $SETZER_MAX_GAS_PRICE ]] || export SETZER_MAX_GAS_PRICE="$max_gas"
 
 # NOTE: Nice way to see if bots are updated. Increase this by 1 on new versions :)
@@ -78,7 +81,7 @@ if ! [[ "$SETZER_BOT_INIT" ]]; then
 
   echo "--------- STARTING SETZER BOT ---------"
   echo "Bot started $(date)"
-  
+
   echo "Default account:     $ETH_FROM"
   echo "Feed address:        $SETZER_FEED"
   echo "Medianizer address:  $SETZER_MEDIANIZER"
@@ -102,7 +105,7 @@ if [ "$expires" -lt "$SETZER_EXPIRES_IN_SECONDS" ]; then
 fi
 
 feed=$(setzer peek "$SETZER_FEED")
-mapfile -t feed <<< "$feed"
+mapfile -t feed <<<"$feed"
 old=${feed[0]}
 
 if [[ $SETZER_SOURCES == *"mkr" ]]; then
@@ -113,11 +116,11 @@ elif [[ $SETZER_SOURCES == *"poly" ]]; then
   new=$(setzer price poly || echo 0)
 elif [[ $SETZER_SOURCES == *"bat" ]]; then
   new=$(setzer price bat || echo 0)
-else 
+else
   new=$(setzer price eth || echo 0)
 fi
 
-check_new=$(bc <<< "$new > 0")
+check_new=$(bc <<<"$new > 0")
 if ! [[ "$check_new" -eq "1" ]]; then
   log "Price was invalid. Waiting 1 minute then trying again"
   sleep 60
@@ -126,7 +129,7 @@ fi
 
 spread=$(setzer spread "$old" "$new")
 log "Old ($old) New ($new) Spread ($spread)"
-test=$(bc <<< "${spread#-} >= $SETZER_SPREAD")
+test=$(bc <<<"${spread#-} >= $SETZER_SPREAD")
 # Check if value has changed more than $SPREAD %
 if [[ ${test} -ne 0 ]]; then
   needsupdate="yes"
@@ -140,7 +143,7 @@ ptn=$PENDING_TRANSACTION_NONCE
 if [[ $ptn ]]; then
   nonce=$(seth nonce "$ETH_FROM")
   verbose "Transaction pending. Checking if nonce $nonce has increased."
-  if [[ "$nonce" -gt "$ptn"  ]]; then
+  if [[ "$nonce" -gt "$ptn" ]]; then
     mined="yes"
     log "SUCCESS! Feed updated. Gas price was $ETH_GAS_PRICE wei"
   else
@@ -152,20 +155,20 @@ if [[ $mined ]]; then
   export PENDING_TRANSACTION_NONCE=
 else
   if [[ $ptn ]]; then
-    loop=$(( CURRENT_LOOP + 1 ))
+    loop=$((CURRENT_LOOP + 1))
     export CURRENT_LOOP="$loop"
-    
+
     current_gas_price=$(seth gas-price)
-    minimum_new_gas_price=$(bc <<< "$ETH_GAS_PRICE * 1.15 / 1")
-    
+    minimum_new_gas_price=$(bc <<<"$ETH_GAS_PRICE * 1.15 / 1")
+
     if [[ $current_gas_price -le $minimum_new_gas_price ]]; then
       new_gas_price=$minimum_new_gas_price
     else
       new_gas_price=$current_gas_price
     fi
-    
+
     export ETH_GAS_PRICE="$new_gas_price"
-    
+
     if [[ $new_gas_price -le $SETZER_MAX_GAS_PRICE ]]; then
       log "New gas price: $ETH_GAS_PRICE"
       needsupdate="yes"
